// Colors
export const colors = {
    // Supporting light and dark themes
    light: {
        defaultBorderColor: '#E1E1E1',
        lightBorderColor: '#F1F1F1',
        darkBorderColor: '#A1A1A1',
        backgroundColor: '#F5F6FA',
        defaultTextColor: '#353535',
        lightTextColor: '#9EA7CA',
        highlightColor: '#FFB17A',
    },
    default: {
        backgroundColor: 'white',
        fillColor: 'transparent',
        color: '#a1a1a1',
        rippleColor: '#a1a1a1',
        active: '#353535',
        hover: '#f6f6f6',
        darkHover: '#919191',
    },
    text: {
        backgroundColor: 'rgba(255, 255, 255, 0)',
        disabledBg: 'rgba(255, 255, 255, 0)',
        disabledColor: '#bdbdbd',
    },
    contained: {
        backgroundColor: 'white',
        disabledBg: 'white',
        disabledColor: '#bdbdbd',
    },
    outlined: {
        backgroundColor: 'white',
        disabledBg: 'white',
        disabledColor: '#bdbdbd',
    },

    primary: {
        backgroundColor: 'white',
        fillColor: 'rgba(0, 71, 190, 0.2)',
        color: '#008ecc',
        rippleColor: '#008ecc',
        active: '#0080b8',
        hover: '#e6f4fa',
        darkHover: '#0080b8',
    },

    secondary: {
        backgroundColor: 'white',
        fillColor: 'rgba(19, 41, 61, 0.2)',
        color: '#13293D',
        rippleColor: '#13293D',
        active: '#425464',
        hover: '#e7eaec',
        darkHover: '#425464',
    },
    info: {
        backgroundColor: 'white',
        fillColor: 'rgba(36, 128, 245, 0.2)',
        color: '#2480f5',
        rippleColor: '#2480f5',
        active: '#1d66c4',
        hover: '#e9f2fe',
        darkHover: '#1d66c4',
    },
    success: {
        backgroundColor: 'white',
        fillColor: 'rgba(91, 149, 64, 0.2)',
        color: '#5b9540',
        rippleColor: '#5b9540',
        active: '#497733',
        hover: '#deead9',
        darkHover: '#497733',
    },
    warning: {
        backgroundColor: 'white',
        fillColor: 'rgba(255, 129, 68, 0.2)',
        color: '#ff8144',
        rippleColor: '#ff8144',
        active: '#e6743d',
        hover: '#fff2ec',
        darkHover: '#e6743d',
    },
    error: {
        backgroundColor: 'white',
        fillColor: 'rgba(255, 67, 67, 0.2)',
        color: '#ff4343',
        rippleColor: '#ff4343',
        active: '#e63c3c',
        hover: '#ffecec',
        darkHover: '#e63c3c',
    },

    variantOptions: {
        text: {
            backgroundColor: 'rgba(255, 255, 255, 0)',
            disabledBg: 'rgba(255, 255, 255, 0)',
            disabledColor: '#bdbdbd',
        },
        contained: {
            backgroundColor: 'white',
            disabledBg: 'white',
            disabledColor: '#bdbdbd',
        },
        outlined: {
            backgroundColor: 'white',
            disabledBg: 'white',
            disabledColor: '#bdbdbd',
        },
    },

    colorOptions: {
        default: {
            backgroundColor: 'white',
            fillColor: 'transparent',
            color: '#a1a1a1',
            rippleColor: '#a1a1a1',
            active: '#353535',
            hover: '#f6f6f6',
            darkHover: '#919191',
        },

        primary: {
            backgroundColor: 'white',
            fillColor: 'rgba(0, 71, 190, 0.2)',
            color: '#008ecc',
            rippleColor: '#008ecc',
            active: '#0080b8',
            hover: '#e6f4fa',
            darkHover: '#0080b8',
        },

        secondary: {
            backgroundColor: 'white',
            fillColor: 'rgba(19, 41, 61, 0.2)',
            color: '#13293D',
            rippleColor: '#13293D',
            active: '#425464',
            hover: '#e7eaec',
            darkHover: '#425464',
        },
        info: {
            backgroundColor: 'white',
            fillColor: 'rgba(36, 128, 245, 0.2)',
            color: '#2480f5',
            rippleColor: '#2480f5',
            active: '#1d66c4',
            hover: '#e9f2fe',
            darkHover: '#1d66c4',
        },
        success: {
            backgroundColor: 'white',
            fillColor: 'rgba(91, 149, 64, 0.2)',
            color: '#5b9540',
            rippleColor: '#5b9540',
            active: '#497733',
            hover: '#deead9',
            darkHover: '#497733',
        },
        warning: {
            backgroundColor: 'white',
            fillColor: 'rgba(255, 129, 68, 0.2)',
            color: '#ff8144',
            rippleColor: '#ff8144',
            active: '#e6743d',
            hover: '#fff2ec',
            darkHover: '#e6743d',
        },
        error: {
            backgroundColor: 'white',
            fillColor: 'rgba(255, 67, 67, 0.2)',
            color: '#ff4343',
            rippleColor: '#ff4343',
            active: '#e63c3c',
            hover: '#ffecec',
            darkHover: '#e63c3c',
        },
    },
};
