import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(dirname, "..");

const FONTS = [
  {
    family: "Inter",
    weight: "100 900",
    file: path.join(root, "src/assets/fonts/InterVariable.woff2"),
    format: "woff2-variations",
  },
];

const output = path.join(root, "src/styles/fonts.generated.css");

const css = FONTS.map(({ family, weight, file, format }) => {
  const base64 = readFileSync(file).toString("base64");
  return [
    "@font-face {",
    `  font-family: "${family}";`,
    "  font-style: normal;",
    `  font-weight: ${weight};`,
    "  font-display: swap;",
    `  src: url(data:font/woff2;base64,${base64}) format("${format}");`,
    "}",
  ].join("\n");
}).join("\n\n");

writeFileSync(
  output,
  `/* Generated by scripts/embed-fonts.mjs. Do not edit by hand. */\n${css}\n`,
);

console.log(`Wrote ${output}`);
